-- Seed COA mengikuti struktur PDF Laporan Laba/Rugi Natura
insert into accounts (code, name, section, category, sign, sort_order) values
  ('4100', 'Penjualan',                                    'revenue',        null,             1,  10),
  ('4110', 'Retur Penjualan',                              'revenue',        null,            -1,  20),
  ('4120', 'Diskon Penjualan',                             'revenue',        null,            -1,  30),
  ('5100', 'Beban Pokok Penjualan',                        'cogs',           null,             1, 100),
  ('6100', 'Beban Gaji, Upah & Honorer',                   'opex', 'Gaji',                     1, 210),
  ('6110', 'Beban Bensin, Parkir, Tol Kendaraan',          'opex', 'Gaji',                     1, 220),
  ('6120', 'Beban Transportasi Karyawan',                  'opex', 'Gaji',                     1, 230),
  ('6130', 'Beban THR',                                    'opex', 'Gaji',                     1, 240),
  ('6140', 'Beban Katering & Makan Karyawan',              'opex', 'Gaji',                     1, 250),
  ('6150', 'Beban Tunjangan Karyawan',                     'opex', 'Gaji',                     1, 260),
  ('6160', 'Beban BPJS Kesehatan',                         'opex', 'Gaji',                     1, 270),
  ('6170', 'Beban BPJS Ketenagakerjaan',                   'opex', 'Gaji',                     1, 280),
  ('6180', 'Beban Pelatihan dan Pengembangan Karyawan',    'opex', 'Gaji',                     1, 290),
  ('6200', 'Beban Listrik',                                'opex', 'Kantor',                   1, 310),
  ('6210', 'Beban Telekomunikasi',                         'opex', 'Kantor',                   1, 320),
  ('6220', 'Beban Ekspedisi, Pos & Materai',               'opex', 'Kantor',                   1, 330),
  ('6230', 'Beban Perjalanan Dinas',                       'opex', 'Kantor',                   1, 340),
  ('6240', 'Beban Perlengkapan Kantor',                    'opex', 'Kantor',                   1, 350),
  ('6250', 'Beban Aplikasi Sistem',                        'opex', 'Kantor',                   1, 360),
  ('6260', 'Beban Peralatan Kantor',                       'opex', 'Kantor',                   1, 370),
  ('6270', 'Beban Perbaikan Alat Kantor',                  'opex', 'Kantor',                   1, 380),
  ('6280', 'Beban R&D',                                    'opex', 'Kantor',                   1, 390),
  ('6290', 'Beban Kebersihan Kantor',                      'opex', 'Kantor',                   1, 400),
  ('6295', 'Beban Jasa Manajemen dan Konsultasi',          'opex', 'Kantor',                   1, 410),
  ('6297', 'Beban Service Alat Kantor',                    'opex', 'Kantor',                   1, 420),
  ('6300', 'Beban Iklan Branding',                         'opex', 'Pemasaran',                1, 510),
  ('6310', 'Beban Iklan Shopee NG',                        'opex', 'Pemasaran',                1, 520),
  ('6320', 'Beban Iklan Tiktok NG',                        'opex', 'Pemasaran',                1, 530),
  ('6330', 'Beban Afiliasi Shopee NG',                     'opex', 'Pemasaran',                1, 540),
  ('6340', 'Beban Afiliasi Tiktok NG',                     'opex', 'Pemasaran',                1, 550),
  ('6350', 'Beban Promo Shopee NG',                        'opex', 'Pemasaran',                1, 560),
  ('6360', 'Beban Iklan Meta',                             'opex', 'Pemasaran',                1, 570),
  ('6400', 'Beban Admin Shopee NG',                        'opex', 'Fee E-Commerce',           1, 610),
  ('6410', 'Beban Admin Tiktok NG',                        'opex', 'Fee E-Commerce',           1, 620),
  ('6420', 'Potongan Ongkos Kirim NG',                     'opex', 'Fee E-Commerce',           1, 630),
  ('6430', 'Beban Proses Pesanan Shopee NG',               'opex', 'Fee E-Commerce',           1, 640),
  ('6440', 'Beban Proses Pesanan TikTok NG',               'opex', 'Fee E-Commerce',           1, 650),
  ('6450', 'Beban Layanan Cashback Bonus TikTok NG',       'opex', 'Fee E-Commerce',           1, 660),
  ('6500', 'Beban Penyusutan Mesin dan Peralatan',         'opex', 'Penyusutan',               1, 710),
  ('6510', 'Beban Penyusutan Inventaris Kantor',           'opex', 'Penyusutan',               1, 720),
  ('6600', 'Beban Packaging',                              'opex', 'Produksi',                 1, 810),
  ('6610', 'Beban Perlengkapan Gudang',                    'opex', 'Produksi',                 1, 820),
  ('6700', 'Beban Operasional Lainnya',                    'opex', 'Ops Lainnya',              1, 910),
  ('6710', 'Beban CSR',                                    'opex', 'Ops Lainnya',              1, 920),
  ('6800', 'Beban Sewa Gedung',                            'opex', 'Sewa',                     1, 1010),
  ('6810', 'Beban Sewa Kendaraan',                         'opex', 'Sewa',                     1, 1020),
  ('7100', 'Penyesuaian Marketplace',                      'non_op_income', null,             -1, 1110),
  ('7110', 'Pendapatan Bunga',                             'non_op_income', null,              1, 1120),
  ('7200', 'Beban Adm. Bank & Buku Cek/Giro',              'non_op_expense', null,             1, 1210),
  ('7210', 'Pajak Jasa Giro',                              'non_op_expense', null,             1, 1220),
  ('7220', 'Beban Penyesuaian Kas Bank',                   'non_op_expense', null,             1, 1230),
  ('9100', 'Pajak Penghasilan',                            'tax',            null,             1, 9000);
